"""empty message

Revision ID: b1ea9aedf189
Revises: 1632978d140f
Create Date: 2020-06-14 15:19:46.407149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ea9aedf189'
down_revision = '1632978d140f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(length=150), nullable=False),
    sa.Column('secret_key', sa.String(length=150), nullable=False),
    sa.Column('ticket_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret')
    # ### end Alembic commands ###
